"""Overnight matrix orchestrator — runs the full training matrix one cell at a time.

Design:
  - Reads a manifest of (algo, env_d4rl_name, dataset, seed, stage, est_hours)
    rows. Default manifest is generated in-code from the active method list
    and the dataset matrix in docs/02; can be overridden via --manifest path.
  - Serial: at most one GPU process at a time (we only have 1 GPU).
  - Each cell launched via subprocess with stdout+stderr to logs/matrix/<key>.log.
  - State file `state/matrix.json` is updated on every transition.
  - On crash → Discord ping (per user policy: failures only).
  - Idempotent restart: re-invoke and any cell whose status is `pending` runs;
    `running` cells whose PID is stale are recovered.

Usage:
    # Generate default manifest + show plan:
    python scripts/long_runner.py --plan

    # Run the matrix (blocking; nohup-able):
    nohup python scripts/long_runner.py --execute > logs/matrix.log 2>&1 &
    echo $! > state/long_runner.pid

    # Resume after reboot / kill:
    python scripts/long_runner.py --execute    # picks up where it left off

    # Status:
    python scripts/long_runner.py --status

    # Mark cells as skipped / re-pending:
    python scripts/long_runner.py --mark <cell_key> --to skipped|pending
"""
from __future__ import annotations

import argparse
import json
import os
import shlex
import signal
import subprocess
import sys
import time
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Optional

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
LOGS = ROOT / "logs" / "matrix"
STATE = ROOT / "state" / "matrix.json"


# Estimated wall-clock per cell on RTX 5090 (rough; refined after smokes).
# These are upper bounds — actual times come from observed timings post-smoke.
EST_HOURS = {
    ("bc",      "halfcheetah"): 0.5,
    ("cql",     "halfcheetah"): 1.5,
    ("iql",     "halfcheetah"): 1.5,
    ("td3bc",   "halfcheetah"): 1.5,
    ("dt",      "halfcheetah"): 1.5,
    ("diffuser","halfcheetah"): 10.0,
    ("dd",      "hopper"):      10.0,
    ("dql",     "halfcheetah"): 6.0,
    ("ldcq",    "halfcheetah"): 15.0,   # 4 stages combined
    ("eda",     "halfcheetah"): 9.0,    # 3 stages combined
    ("qgpo",    "halfcheetah"): 10.0,   # 2 stages combined
    # Humanoid is ~3x slower per cell due to bigger state space:
    ("ldcq",    "humanoid"):    45.0,
    ("eda",     "humanoid"):    27.0,
    ("qgpo",    "humanoid"):    30.0,
}


# (algo, env_d4rl_name, dataset, seed, stage, launcher, extra_args, est_hours)
# Generated by `_default_manifest()` below. Override via --manifest.


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _env_short(env_d4rl_name: str) -> str:
    return env_d4rl_name.split("-")[0]


def _est_hours(algo: str, env_d4rl_name: str, multi_stage_fraction: float = 1.0) -> float:
    base = EST_HOURS.get((algo, _env_short(env_d4rl_name)), 5.0)
    return base * multi_stage_fraction


def _default_manifest() -> list[dict]:
    """Default Phase 6 matrix per docs/02 + docs/05.

    Active methods (Option C, this session's dataset namespace) on the 4 envs
    × {medium, expert}-v0 splits. Each cell × 3 seeds. The Phase 5
    'verify-defaults' gate runs FIRST as 1 seed per cell to catch issues
    early; long matrix uses 3 seeds.
    """
    rows = []
    # Pool defaults to "default" — set explicitly so --pool filtering works.
    # User can move cells to a different pool via cmd_reassign for multi-host
    # split.
    _POOL = "default"

    def _mk(**kw):
        kw.setdefault("status", "pending")
        kw.setdefault("started_at", None)
        kw.setdefault("finished_at", None)
        kw.setdefault("pid", None)
        kw.setdefault("rc", None)
        kw.setdefault("attempts", 0)
        kw.setdefault("pool", _POOL)
        return kw

    # CORL methods × 3 envs × 2 splits × 3 seeds (no Humanoid by decision D4)
    for algo in ("bc", "cql", "iql", "td3bc", "dt"):
        for env in ("halfcheetah", "hopper", "walker2d"):
            for split in ("medium", "expert"):
                d4rl = f"{env}-{split}-v0"
                for seed in (0, 1, 2):
                    rows.append(_mk(
                        key=f"{algo}_{d4rl}_seed{seed}_full",
                        algo=algo, env_d4rl_name=d4rl, dataset=split, seed=seed,
                        stage="full", launcher="run_corl.py",
                        extra_args=["--algo", algo],
                        est_hours=_est_hours(algo, d4rl),
                    ))

    # Diffuser × 3 envs × 2 splits × 3 seeds (no Humanoid by decision D5)
    for env in ("halfcheetah", "hopper", "walker2d"):
        for split in ("medium", "expert"):
            d4rl = f"{env}-{split}-v0"
            for seed in (0, 1, 2):
                rows.append(_mk(
                    key=f"diffuser_{d4rl}_seed{seed}_full",
                    algo="diffuser", env_d4rl_name=d4rl, dataset=split, seed=seed,
                    stage="full", launcher="run_diffuser.py",
                    extra_args=["--algo", "diffuser"],
                    est_hours=_est_hours("diffuser", d4rl),
                ))

    # DD dropped from the matrix (user 2026-05-19). It needs params_proto +
    # ml_logger + jaynes deps AND Option-B `hopper-medium-expert-v2` data,
    # neither of which we have this session. Reasoning + cite mirrored to
    # baselines/RUN_LOG.md patch #28. Same pattern as the LDCQ drop.

    # DQL × 3 envs × 2 splits × 3 seeds
    for env in ("halfcheetah", "hopper", "walker2d"):
        for split in ("medium", "expert"):
            d4rl = f"{env}-{split}-v0"
            for seed in (0, 1, 2):
                rows.append(_mk(
                    key=f"dql_{d4rl}_seed{seed}_full",
                    algo="dql", env_d4rl_name=d4rl, dataset=split, seed=seed,
                    stage="full", launcher="run_dql.py", extra_args=["--algo", "dql"],
                    est_hours=_est_hours("dql", d4rl),
                ))

    # LDCQ is dropped from the baselines matrix this session (user 2026-05-19).
    # Eager chunk-extraction in train_skills.py allocates ~40 GB per Humanoid
    # env on this host's 62 GB RAM, triggering OOM-killer. Will be reproduced
    # on a higher-RAM system separately. See baselines/RUN_LOG.md task #17.
    # The autoresearch smokes for LDCQ HalfCheetah passed and are recorded
    # in latent_cep_baselines_smoke MLflow experiment for forensics.

    # EDA × 4 envs × 2 splits × 3 seeds × 3 stages
    for env in ("halfcheetah", "hopper", "walker2d", "humanoid"):
        for split in ("medium", "expert"):
            d4rl = f"{env}-{split}-v0"
            for seed in (0, 1, 2):
                for stage in ("behavior", "critic", "finetune"):
                    rows.append(_mk(
                        key=f"eda_{d4rl}_seed{seed}_{stage}",
                        algo="eda", env_d4rl_name=d4rl, dataset=split, seed=seed,
                        stage=stage, launcher="run_eda.py",
                        extra_args=["--algo", "eda", "--stage", stage],
                        est_hours=_est_hours("eda", d4rl) / 3.0,
                    ))

    # QGPO × 4 envs × 2 splits × 3 seeds × 2 stages
    for env in ("halfcheetah", "hopper", "walker2d", "humanoid"):
        for split in ("medium", "expert"):
            d4rl = f"{env}-{split}-v0"
            for seed in (0, 1, 2):
                for stage in ("behavior", "critic"):
                    rows.append(_mk(
                        key=f"qgpo_{d4rl}_seed{seed}_{stage}",
                        algo="qgpo", env_d4rl_name=d4rl, dataset=split, seed=seed,
                        stage=stage, launcher="run_qgpo.py",
                        extra_args=["--algo", "qgpo", "--stage", stage],
                        est_hours=_est_hours("qgpo", d4rl) / 2.0,
                    ))
    return rows


def load_state() -> dict:
    if STATE.exists():
        try:
            return json.loads(STATE.read_text())
        except Exception:
            pass
    return {"version": 1, "started_at": _now(), "rows": _default_manifest()}


def save_state(s: dict) -> None:
    STATE.parent.mkdir(parents=True, exist_ok=True)
    tmp = STATE.with_suffix(".tmp")
    tmp.write_text(json.dumps(s, indent=2))
    tmp.replace(STATE)


def _send_discord(level: str, task: str, msg: str) -> None:
    sys.path.insert(0, str(SCRIPTS))
    try:
        from notify import send  # type: ignore
        send(level, task, msg)
    except Exception:
        pass


def _pid_alive(pid: int) -> bool:
    try:
        os.kill(pid, 0)
        return True
    except OSError:
        return False


def cmd_plan(state: dict) -> int:
    rows = state["rows"]
    total_hours = sum(r["est_hours"] for r in rows if r["status"] == "pending")
    print(f"Manifest: {len(rows)} cells")
    print(f"  by status:")
    for s in ("pending", "running", "green", "red", "skipped"):
        n = sum(1 for r in rows if r["status"] == s)
        print(f"    {s:>8}: {n}")
    print(f"  pending total est: {total_hours:.1f}h = {total_hours/24:.2f}d (serial, 1 GPU)")
    print()
    print(f"{'status':<9} {'est_h':>6} {'cell'}")
    for r in rows[:20]:
        print(f"{r['status']:<9} {r['est_hours']:>6.2f} {r['key']}")
    if len(rows) > 20:
        print(f"... ({len(rows) - 20} more)")
    return 0


def cmd_status(state: dict) -> int:
    rows = state["rows"]
    by_status = {}
    for r in rows:
        by_status.setdefault(r["status"], []).append(r)
    print(f"{'status':<9}  {'cells'}")
    for s in ("running", "pending", "green", "red", "skipped"):
        cells = by_status.get(s, [])
        print(f"  {s:<8}  {len(cells)}")
    print()
    running = by_status.get("running", [])
    for r in running:
        elapsed = ""
        if r.get("started_at"):
            t0 = datetime.fromisoformat(r["started_at"].replace("Z", "+00:00"))
            dt = datetime.now(timezone.utc) - t0
            elapsed = f"  elapsed={str(dt).split('.')[0]}"
        print(f"  RUNNING: {r['key']}  pid={r.get('pid')}{elapsed}")
    return 0


# ----- bin-packing scheduler helpers -----

# Conservative GPU + system-RAM budget on a 32 GB RTX 5090 / 62 GB host.
GPU_VRAM_BUDGET_GB = 28.0
SYSTEM_RAM_BUDGET_GB = 45.0
# Hard floor: if available RAM ever drops below this we DON'T launch more
# (prevents recurrence of the LDCQ Humanoid OOM-killer incident).
RAM_AVAIL_FLOOR_GB = 5.0
# Same floor for GPU memory.
VRAM_FREE_FLOOR_GB = 2.0

# Per-process safety multiplier on the footprint peak. The smoke peaks were
# captured for a few minutes; long runs may have higher real peaks, so we
# overestimate budget consumption by 1.3× to avoid OOMs.
FOOTPRINT_SAFETY = 1.3


def _load_footprints() -> dict:
    """Return per-algo {peak_vram_gb, peak_ram_gb} dict from autoresearch state."""
    agg_path = ROOT / "state" / "footprints" / "_aggregate.json"
    if not agg_path.exists():
        return {}
    try:
        data = json.loads(agg_path.read_text())
    except Exception:
        return {}
    out = {}
    for algo, v in data.get("per_algo_max_across_stages", {}).items():
        out[algo] = {
            "vram_gb": float(v.get("vram_peak_gb", 0.0)),
            "ram_gb":  float(v.get("rss_peak_gb",  0.0)),
        }
    return out


def _row_budget(row: dict, footprints: dict) -> tuple[float, float]:
    """Return (vram_gb, ram_gb) reservation for a cell, with safety margin."""
    fp = footprints.get(row["algo"], {})
    vram = fp.get("vram_gb", 4.0) * FOOTPRINT_SAFETY  # default 4 GB if unknown
    ram  = fp.get("ram_gb",  4.0) * FOOTPRINT_SAFETY
    # Humanoid: ~3× scale-up for obs-dim heavy methods. We don't have a
    # full Humanoid footprint for every method yet — keep a safety bump.
    if "humanoid" in row["env_d4rl_name"]:
        vram *= 1.8
        ram  *= 1.8
    return max(vram, 0.5), max(ram, 0.5)


def _gpu_free_gb() -> float:
    """Free vRAM on GPU 0 in GB."""
    try:
        out = subprocess.check_output(
            ["nvidia-smi", "--query-gpu=memory.free", "--format=csv,noheader,nounits", "--id=0"],
            stderr=subprocess.DEVNULL, timeout=5,
        ).decode().strip()
        return float(out) / 1024.0
    except Exception:
        return float("inf")


def _ram_avail_gb() -> float:
    """Available system RAM in GB (reads /proc/meminfo)."""
    try:
        with open("/proc/meminfo") as f:
            for line in f:
                if line.startswith("MemAvailable:"):
                    kb = int(line.split()[1])
                    return kb / (1024.0 ** 2)
    except Exception:
        return float("inf")
    return float("inf")


def _launch_one(row: dict, env: dict, log_path: Path) -> subprocess.Popen:
    cmd = [
        sys.executable, str(SCRIPTS / row["launcher"]),
        *row["extra_args"],
        "--env_d4rl_name", row["env_d4rl_name"],
        "--seed", str(row["seed"]),
        "--stage", row["stage"],
    ]
    LOGS.mkdir(parents=True, exist_ok=True)
    log_path.parent.mkdir(parents=True, exist_ok=True)
    logf = open(log_path, "ab")
    # Per-process thread caps so a 4-process cohort doesn't blow CPU.
    proc_env = dict(env)
    proc_env.setdefault("OMP_NUM_THREADS", "4")
    proc_env.setdefault("MKL_NUM_THREADS", "4")
    proc_env.setdefault("OPENBLAS_NUM_THREADS", "4")
    proc_env.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")
    proc = subprocess.Popen(cmd, env=proc_env, cwd=str(ROOT),
                            stdout=logf, stderr=subprocess.STDOUT,
                            preexec_fn=os.setsid)
    return proc


def _on_cell_finished(row: dict, proc: subprocess.Popen, log_path: Path) -> None:
    """Mark a finished cell green/red/skipped + ping Discord on failure."""
    rc = proc.returncode
    row["pid"] = None
    row["rc"] = rc
    row["finished_at"] = _now()
    if rc == 0:
        row["status"] = "green"
        print(f"  ✓ green   {row['key']}")
    elif rc == 64:
        row["status"] = "skipped"
        row["notes"] = "launcher rc=64 (explicit skip)"
        print(f"  ⊘ skipped {row['key']}")
    elif rc == 65:
        row["status"] = "awaiting_prereq"
        row["notes"] = "launcher rc=65 (missing prerequisite)"
        print(f"  · awaiting_prereq {row['key']}")
    else:
        row["status"] = "red"
        row["notes"] = f"rc={rc}"
        tail = ""
        try:
            with open(log_path, "rb") as f:
                size = f.seek(0, 2)
                f.seek(max(0, size - 1500))
                tail = f.read().decode("utf-8", errors="replace")
        except Exception:
            pass
        _send_discord("failure", f"matrix:{row['key']}",
                      f"rc={rc}. Tail:\n```\n{tail[-1200:]}\n```")
        print(f"  ✗ red     {row['key']}  rc={rc} (discord ping)")


def cmd_execute(state: dict, pool: str = "default", max_concurrency: int = 8,
                heavy_first: bool = False) -> int:
    """Bin-packing scheduler with OOM safety.

    Default ordering is "easy-first" (sort pending by ascending est_hours): quick
    wins surface fast, and heaviest jobs run alone at the end when the queue is
    small anyway. Pass heavy_first=True for Worst-Fit-Decreasing (best packing
    density but slower early throughput).
    """
    rows = state["rows"]
    footprints = _load_footprints()
    if footprints:
        print(f"loaded footprints for {len(footprints)} algos: "
              + ", ".join(sorted(footprints.keys())))
    else:
        print("WARN: no footprints aggregate found; using default 4 GB / 4 GB per cell")

    env = os.environ.copy()
    env["MLFLOW_TRACKING_URI"] = env.get("MLFLOW_TRACKING_URI", "http://localhost:5555")
    env["MLFLOW_EXPERIMENT_NAME"] = "latent_cep_baselines"
    env["DATASET_OPTION"] = env.get("DATASET_OPTION", "C")

    # Recover stale 'running' cells whose PID is gone.
    for r in rows:
        if r["status"] == "running":
            pid = r.get("pid")
            if pid and not _pid_alive(pid):
                r["status"] = "pending"
                r["notes"] = f"recovered: pid {pid} gone on restart"
                r["pid"] = None
    save_state(state)

    pending = [r for r in rows
               if r["status"] == "pending" and r.get("pool", "default") == pool]
    if not pending:
        print(f"No pending cells in pool {pool!r}; nothing to do.")
        return 0

    if heavy_first:
        # Worst-Fit-Decreasing: sort by est_hours descending
        pending.sort(key=lambda r: -r["est_hours"])
    else:
        # Easy-first: sort by est_hours ascending
        pending.sort(key=lambda r: r["est_hours"])

    print(f"\nScheduling pool={pool!r}  "
          f"order={'heavy-first' if heavy_first else 'easy-first'}  "
          f"max_concurrency={max_concurrency}")
    print(f"  pending = {len(pending)} cells, est serial = "
          f"{sum(r['est_hours'] for r in pending):.1f}h")
    print(f"  budget  = vRAM {GPU_VRAM_BUDGET_GB:.0f} GB, RAM {SYSTEM_RAM_BUDGET_GB:.0f} GB, "
          f"floor RAM≥{RAM_AVAIL_FLOOR_GB:.0f} GB and vRAM_free≥{VRAM_FREE_FLOOR_GB:.0f} GB\n")

    running: list[tuple[subprocess.Popen, dict, Path, float, float]] = []  # (proc, row, log, vram, ram)
    poll_interval = 15

    def _used_vram() -> float: return sum(r[3] for r in running)
    def _used_ram()  -> float: return sum(r[4] for r in running)

    try:
        while pending or running:
            # Reap finished
            still = []
            for proc, row, log, v, m in running:
                if proc.poll() is None:
                    still.append((proc, row, log, v, m))
                else:
                    _on_cell_finished(row, proc, log)
                    save_state(state)
            running = still

            # Admit pending cells if budget + OOM-floor both allow
            avail_ram = _ram_avail_gb()
            free_vram = _gpu_free_gb()
            if avail_ram < RAM_AVAIL_FLOOR_GB or free_vram < VRAM_FREE_FLOOR_GB:
                # Don't admit anything; wait for some running to free up
                pass
            else:
                admit_i = 0
                while admit_i < len(pending) and len(running) < max_concurrency:
                    row = pending[admit_i]
                    vram, ram = _row_budget(row, footprints)
                    if (_used_vram() + vram <= GPU_VRAM_BUDGET_GB
                        and _used_ram() + ram <= SYSTEM_RAM_BUDGET_GB):
                        # Launch
                        row["status"] = "running"
                        row["started_at"] = _now()
                        row["attempts"] = row.get("attempts", 0) + 1
                        row["budget_vram_gb"] = vram
                        row["budget_ram_gb"]  = ram
                        log_path = LOGS / f"{row['key']}.log"
                        save_state(state)
                        proc = _launch_one(row, env, log_path)
                        row["pid"] = proc.pid
                        save_state(state)
                        running.append((proc, row, log_path, vram, ram))
                        print(f"  ▶ launched {row['key']}  "
                              f"(vram_budget={vram:.1f}GB ram_budget={ram:.1f}GB; "
                              f"now running={len(running)}, used={_used_vram():.1f}/{_used_ram():.1f} GB)")
                        pending.pop(admit_i)
                    else:
                        admit_i += 1

            # Sleep if nothing changed
            if running:
                time.sleep(poll_interval)
            elif pending:
                # Pending but couldn't admit anything (probably hit OOM floor)
                print(f"  · idle: pending={len(pending)} but admission blocked "
                      f"(avail_ram={avail_ram:.1f}GB free_vram={free_vram:.1f}GB)")
                time.sleep(poll_interval * 2)

    except KeyboardInterrupt:
        print("\n! interrupted — leaving running cells alone for resume")
        return 130

    # All done
    n_g = sum(1 for r in rows if r["status"] == "green")
    n_r = sum(1 for r in rows if r["status"] == "red")
    n_s = sum(1 for r in rows if r["status"] == "skipped")
    print(f"\n=== matrix complete: green={n_g} red={n_r} skipped={n_s}")
    return 0 if n_r == 0 else 1


def cmd_reassign_pool(state: dict, pattern: str, to_pool: str) -> int:
    """Move cells matching a substring pattern to a different pool.

    Cells with pool != 'default' are skipped by the local scheduler — useful
    for splitting work across machines."""
    n = 0
    for r in state["rows"]:
        if pattern in r["key"]:
            r["pool"] = to_pool
            n += 1
    save_state(state)
    print(f"reassigned {n} cells matching {pattern!r} to pool {to_pool!r}")
    return 0


def cmd_export_pool(state: dict, pool: str, out_path: str) -> int:
    """Export the subset of cells in a given pool to a portable JSON file.

    The other server runs `long_runner.py --execute --pool <name>` against the
    exported manifest after scp'ing it over. The local state file should be
    edited to mark those cells `delegated` so the local scheduler skips them.
    """
    cells = [r for r in state["rows"] if r.get("pool", "default") == pool]
    if not cells:
        print(f"no cells in pool {pool!r}", file=sys.stderr)
        return 1
    out = {"version": 1, "exported_at": _now(), "rows": cells}
    Path(out_path).write_text(json.dumps(out, indent=2))
    print(f"wrote {out_path} with {len(cells)} cells")
    # Mark as delegated so local scheduler skips them.
    for r in state["rows"]:
        if r.get("pool") == pool:
            r["status"] = "delegated"
    save_state(state)
    return 0


def cmd_mark(state: dict, key: str, to: str) -> int:
    if to not in ("pending", "skipped", "green", "red"):
        print(f"bad --to {to!r}", file=sys.stderr)
        return 2
    for r in state["rows"]:
        if r["key"] == key:
            r["status"] = to
            r["notes"] = f"marked {to} by operator at {_now()}"
            save_state(state)
            print(f"marked {key} -> {to}")
            return 0
    print(f"cell not found: {key}", file=sys.stderr)
    return 1


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--plan",     action="store_true")
    p.add_argument("--status",   action="store_true")
    p.add_argument("--execute",  action="store_true")
    p.add_argument("--pool",     default="default",
                   help="Only run cells whose pool field matches this string.")
    p.add_argument("--max_concurrency", type=int, default=8,
                   help="Cap on simultaneous running cells (default 8). "
                        "Resource budget still enforced.")
    p.add_argument("--heavy_first", action="store_true",
                   help="Order pending by est_hours descending (Worst-Fit-"
                        "Decreasing). Default is easy-first.")
    p.add_argument("--mark",    default=None, help="cell key to mark")
    p.add_argument("--to",      default=None, help="target status for --mark")
    p.add_argument("--reassign", default=None,
                   help="Move cells whose key contains this pattern to "
                        "--to-pool.")
    p.add_argument("--to_pool", default=None,
                   help="Destination pool for --reassign or --export-pool.")
    p.add_argument("--export_pool", action="store_true",
                   help="Export cells in --pool to a portable manifest.")
    p.add_argument("--out",      default=None,
                   help="Output path for --export_pool.")
    args = p.parse_args()

    state = load_state()
    save_state(state)
    if args.plan:    return cmd_plan(state)
    if args.status:  return cmd_status(state)
    if args.execute:
        return cmd_execute(state, pool=args.pool,
                           max_concurrency=args.max_concurrency,
                           heavy_first=args.heavy_first)
    if args.mark:
        if not args.to:
            print("--to is required with --mark", file=sys.stderr)
            return 2
        return cmd_mark(state, args.mark, args.to)
    if args.reassign:
        if not args.to_pool:
            print("--to_pool is required with --reassign", file=sys.stderr)
            return 2
        return cmd_reassign_pool(state, args.reassign, args.to_pool)
    if args.export_pool:
        if not args.out:
            print("--out is required with --export_pool", file=sys.stderr)
            return 2
        return cmd_export_pool(state, args.pool, args.out)
    p.print_help()
    return 0


if __name__ == "__main__":
    sys.exit(main())
